<<Анализ требований>>


== Анализ требований

. Питание платы должно быть автономным и подаваться с солнечный батарей 

. Период измерения должен быть 100 ms

. Измерямые физические величины: давления, влажности и температуры, точка росы

. Общение с датчиком должно осуществляться по интерфейсу SPI4

. Общение с платной модуля BlueTooth должна осуществляться через USART2

. Период вывода информации через BlueTooth модуль должен быть 1 секунда.

== Питание
. Питание - даташит на stm узнать при какой частоте работы будет потребление, указать при какой оптимальной скорости могу работать

== Давление

. Единицы измерения -  

. При включеном БИХ-фильтр, разрешение давления составляет 20 бит.

. При выключеном БИХ-фильтр, разрешение давления составляет 16 + (osrs_p – 1) бит, например 18 бит
когда для osrs_p установлено значение «3».

. Регистр «ctrl_meas» (0xF4) устанавливает параметры сбора данных о давлении и температуре.


== Влажность

. Единицы измерения -

. Разрешение измерения влажности фиксировано на выходе 16-битного АЦП.

. Регистр «ctrl_hum» (0xF2) устанавливает параметры сбора данных о влажности устройства.



== Температуры

. Единицы измерения -

. При включеном БИХ-фильтр, разрешение давления составляет 20 бит.

. При выключеном БИХ-фильтр, разрешение давления составляет 16 + (osrs_p – 1) бит, например 18 бит
когда для osrs_p установлено значение «3».

. Регистр «ctrl_meas» (0xF4) устанавливает параметры сбора данных о давлении и температуре.

== Точка росы

. Единицы измерения - градусы цельсии 

. Точка росы должна считаться на основе текущих показаний влажности и давления ?

. Точка росы зависит от:

.. Температуры.
.. Относительной влажности воздуха.

Чем выше относительная влажность воздуха, тем выше значение точки росы, соответственно, чем меньше влажность, тем она ниже.





== SPI4
. В работе будет использоваться SPI control register 4 (SPI_CR4)

. Время опрашивания 100 мс

. Для этого нужно выставить:
* [*] Бит 2 MSTR: выбор ведущего устройства:

0: Конфигурация подчиненного устройства;

1: Основная конфигурация.

 
* [*] Биты 5:3 BR[2:0]: контроль скорости передачи данных:

000: fPCLK/2;

001: fPCLK/4;

010: fPCLK/8;

011: fPCLK/16;

100: fPCLK/32;

101: fPCLK/64;

110: fPCLK/128;

111: fPCLK/256.
 
* [*] Бит 6 SPE: включение SPI:

0: Периферийное устройство отключено;

1: Периферийное устройство включено.
 
* [*] Бит 7 LSBFIRST: формат кадра:

0: старший бит передается первым

1: младший бит передается первым
 
* [*] Бит 11 DFF: формат кадра данных:

0: для передачи/приема выбран 8-битный формат кадра данных.

1: для передачи/приема выбран 16-битный формат кадра данных.

== USART2

. Настройка бит USART2

. Настройка времени на 1 секунду


== SPI_BME280

. Интерфейс SPI 3 или 4 проводный

. Для доступа на запись передается байт 0x77

. Для доступа на чтение передается байт 0xF7.