include::Tityl_list_3.adoc[lines=1..10]
[.text-right]

Лабораторная работа 2
include::Tityl_list_3.adoc[lines="12..25"]


<<Цель отчета>>

<<Регистр>>

<<Ссылка>>

<<Вывод по работе>>

== Цель отчета

. Изучить Регистр, а именно:
.. Регистр общего назначения
.. Операторные регистр
.. Вспомогательные регистры
.. Специальные регистры

. Работа с регистрами периферии через обертку на С++

== Регистр


Регистры – это специальные ячейки памяти, расположенные непосредственно в процессоре. Работа с регистрами выполняется намного быстрее, чем с ячейками оперативной памяти, поэтому регистры активно используются как в программах на языке ассемблера, так и компиляторами языков высокого уровня.

. Существуют регистры общего назначения и специальные регистры. Регистры общего назначения расположены внутри ядра микроконтроллера (сверхбыстрая память)

. Регистры общего назначения - это сверхбыстрая память внутри процессора, предназначенная для хранения адресов и промежуточных результатов вычислений (регистр общего назначения/регистр данных) или данных, необходимых для работы самого процессора.

. Регистры специального назначения расположены в ОЗУ микроконтроллера и используются для управления процессором и периферийными устройствами.

. Каждый регистр в архитектуре ARM представляет собой ресурс памяти и имеет длину в 32 бита, где каждый бит можно представить в виде выключателя с помощью которого осуществляется управление тем или иным параметром микроконтроллера.
ы















<1> dsa
<2> dsad
<3> dsad

[source, cpp]
----
int main() 
{
  int c = 463 ;
  int* ptr = &c ;
  return 0;
}
----
* [*] 


