:figure-caption: Рисунок
:table-caption: Таблица

include::Tityl_list_3.adoc[lines=1..10]
[.text-right]

Лабораторная работа 5
include::Tityl_list_3.adoc[lines="12..25"]


<<Цель отчета>>

<<Класс>>

<<Мигание светодиодов в режиме шахматы>>

<<Вывод по работе>>

== Цель отчета

. Разобраться что такое класс:

.. Наследование классов.

. На освное полученныех знаний создать класс ChessMode, отвечающий  за переключение светодиодов в шахматном порядке, с наследованием класса Mode.

== Класс

Класс - это пользовательские типы данных, в которых хранятся поля, объявления внутри class по умолчанию приватны.

Класс задаёт тип данных, но дополнительно определяет его поведение. Переменные этого типа по традиции называются объектами.

Наследование представляет один из ключевых аспектов объектно-ориентированного программирования, который позволяет наследовать функциональность одного класса (базового класса) в другом - производном классе.

* [*] Базовые спецификации могут содержать описатель доступа, который является одним из ключевое слово public или protected private. Эти описатели доступа отображаются перед именем базового класса и применяются только к базовому классу. Эти описатели контролируют разрешение производного класса на использование членов базового класса.

* [*] Если описатель доступа опущен, считается, что доступ к этой базе считается private. Базовые спецификации могут содержать ключевое слово virtual для указания виртуального наследования. Это ключевое слово может отображаться до или после описателя доступа, если таковые имеются. Если используется виртуальное наследование, базовый класс называется виртуальным базовым классом.

* [*] Можно определить несколько базовых классов, разделив их запятыми. Если указан один базовый класс, модель наследования является одним наследованием. Если указано несколько базовых классов, модель наследования называется множественным наследованием.


== Мигание светодиодов в режиме шахматы

* Листинг main.cpp:



* Листинг класса Pin3.h 



== Вывод по работе
* [*] Изучено что такое порт; 
* [*] Изучены режимы работы портов; 
* [*] Реализовано мигание светодиодов в режиме ёлочка используя порты и классы.

