:figure-caption: Рисунок
:table-caption: Таблица

include::Tityl_list_3.adoc[lines=1..10]
[.text-right]

Лабораторная работа 4
include::Tityl_list_3.adoc[lines="12..25"]


<<Цель отчета>>

<<Порт>>

<<Режимы работы портов>>

<<Мигание светодиодов в режиме ёлочка>>

<<Вывод по работе>>

== Цель отчета

. Изучить что такое порт. 
. Изучить режимы работы портов. 
. Реализовать мигание светодиодов в режиме ёлочка используя: 
.. порты
.. класс.

== Порт

Порты микроконтроллера - это устройства ввода/вывода, позволяющие микроконтроллеру передавать или принимать данные.

Стандартный порт микроконтроллера AVR имеет восемь разрядов данных, которые могут передаваться или приниматься параллельно. Каждому разряду (или биту) соответствует вывод (ножка) микроконтроллера.

 
Ножки микроконтроллера также называют пинами. Для обозначения портов используются латинские буквы А, В, С и т.д. Количество портов ввода/вывода варьируется в зависимости от модели микроконтроллера.


== Режимы работы портов
Режимы работы портов:

. Плавающий цифровой вход;
. Цифровой вход с подтяжкой к 1 (+3В), подтяжка к логической 1 или 0 осуществляется через резистор (внешняя), либо установкой бита в программе (внутренней);

. Цифровой вход с подтяжкой к 0 (GND);​

. Аналоговый;​

. Цифровой выход с открытым коллектором с подтяжкой к +3В или к GND;

. Цифровой двухтактный выход с подтяжкой к +3В или к GND.

. Альтернативная функция с открытым коллектором с подтяжкой к +3В или к GND;

. Альтернативная функция двухтактный выход с подтяжкой к +3В или к GND.

* [*] Работа в цифровом режиме - порт имеет два состояния: high (true) или low (false).

* [*] Цифровой вход - на контакт порта не подается +3В или GND, в таком случае у порта появляется плавающая ножка. На эту ножку может воздействовать помеха, помеха может случайным образом  устанавливать +3В или GND, это может повлиять на работу порта.  

* [*] Цифровой выход - данный режим позволяет управлять ножками порта, устанавливать логические уровни 1 (High) или 0 (Low), 

* [*] Аналоговый вход - может преобразовывать непрерывный сигнал в дискретное мультибитовое двоичное число в микроконтроллере.

* [*] Аналоговый выход - может преобразовывать мультибитовое двоичное число из микроконтроллера в непрерывный сигнал.


== Мигание светодиодов в режиме ёлочка
* Листинг main.cpp:

[source, cpp]
----
#include "rccregisters.hpp" // for RCC
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPIOэ
#include "tim1registers.hpp"

#include "pin3.h"
#include "PinAll.h"

std::uint32_t SystemCoreClock = 16'000'000U;

extern "C" {
int __low_level_init(void)
{
  
  RCC::CR::HSION::On::Set(); // Включаем внутренний генератор
  
  while (RCC::CR::HSIRDY::NotReady::IsSet()) // пустой цикл для ожидание пока внутренний генератор не настроится
  {

  }
  
  RCC::CR::PLLON::On::Set(); // Включение ФАПЧ
  
  *reinterpret_cast<std::uint32_t*>(0x40023804) &= 0; // Сброс всех битов в 0
  
  RCC::PLLCFGR::PLLSRC::HsiSource::Set(); // Включение тактирования от внутреннего высокочастотного генератора
  
  RCC::PLLCFGR::PLLP0::Pllp2::Set(); // устанавливаем занчение PLLP равным 2
  
  *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 5U); // устанавливаем занчение PLLM равным 32
  
  *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 13U); // устанавливаем занчение PLLN равным 128
  
  while (RCC::CR::PLLRDY::Unclocked::IsSet()) // пустой цикл для ожидания пока внутренний генератор не настроится
  {
    
  }
  
  RCC::CFGR::SW::Pll::Set(); // выбор на коммутататоре сигнала с ФАПЧ
  
  while (!RCC::CFGR::SWS::Pll::IsSet()) // пустой цикл для ожидания пока коммутатор не будет готов
  {
    
  }
  RCC::APB2ENR::SYSCFGEN::Enable::Set();

  return 1;
}
}


void delay(int cycles)
{
  for(int i = 0; i < cycles; ++i)    
  {   
    asm volatile("");
  }    
}

Pin<GPIOA, 5>  pin1;
Pin<GPIOC, 9>  pin2;
Pin<GPIOC, 8>  pin3;
Pin<GPIOC, 5>  pin4;
Pins<pin1, pin2, pin3, pin4> pins;

int main()
{  
  // Подать тактирование на порт А
  RCC::AHB1ENR::GPIOAEN::Enable::Set() ;
  // Подать тактирование на порт А
  RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
  // Порт  А.5 на вывод
  GPIOA::MODER::MODER5::Output::Set() ;
  // Порта С.5,С.8,С.9 на вывод
  GPIOC::MODER::MODER5::Output::Set() ;
  GPIOC::MODER::MODER8::Output::Set() ;
  GPIOC::MODER::MODER9::Output::Set() ;
  
  for(;;)
  {
      pins.ToggleAll();
  }
  
  return 1;
}
----

* Листинг класса Pin3.h 

[source, cpp]
----
#ifndef PIN
#define PIN
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPIOC

template <typename Port, int pinNumber>
class Pin 
{
public: 
  void Toggle() 
  {
    Port::ODR::Toggle(1<<pinNumber);
  }
};
#endif
----

* Листинг класса PinAll.h 

[source, cpp]
----
#ifndef PINS
#define PINS
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPIOC



template <auto& pin1, auto& pin2, auto& pin3, auto& pin4>
class Pins 
{
public:
  void delay(int cycles)
  {
    for(int i = 0; i < cycles; ++i)    
    {   
      asm volatile("");
    }    
  }
  void ToggleAll() 
  {
    pin4.Toggle();
    delay(1000000);
   
    pin3.Toggle();
    delay(1000000);
    
    pin2.Toggle();
    delay(1000000);
    
    pin1.Toggle();
    delay(1000000);
  }
};
#endif
----

== Вывод по работе
* [*] Изучено что такое порт; 
* [*] Изучены режимы работы портов; 
* [*] Реализовано мигание светодиодов в режиме ёлочка используя порты и классы.

