:figure-caption: Рисунок
:table-caption: Таблица

include::Tityl_list_3.adoc[lines=1..10]
[.text-right]

Лабораторная работа 7
include::Tityl_list_3.adoc[lines="12..25"]


<<Цель отчета>>

<<Что такое таймер>>

<<Настройка таймер TIM5>>

<<Программа с таймером TIM5>>

<<Вывод по работе>>

== Цель отчета

. Изучить что такое таймер 

. Настройка таймер TIM5

. Написать программу, где задержка изменения состояние светодиода реализована через TIM5

== Что такое таймер

* [*] Таймер микроконтроллера – это цифровой счётчик, осуществляющий подсчёт количества подаваемых на него импульсов. Источником импульсов для таймера-счётчика могут служить: как тактовые импульсы от внутреннего генератора МК, так и импульсы, подаваемые непосредственно на вход таймера с внешнего источника.

Таймеры нужны для точного отсчета времени, измерения частоты/периода, генерации ШИМ (широтно-импульсной модуляции) и переменных сигналов. Всего есть следующие виды таймеров:

. SYSTEM TIMER. Также существуют системный таймер SysTick таймер и Watchdog таймер.

. Расширенный 16 битный таймер автоматической перезагрузки, приводимого в действие программируемым прескалером.

. 16-разрядные или 32-разрядные таймеры общего назначения автоматической перезагрузки, приводимого в действие программируемым прескалером.

В работе будет использоваться таймер TIM5:

* [*] Таймер 32 битный, может считать до 2^32, умеет работать с инкрементальными энкодерами и датчиками Холла;

== Настройка таймер TIM5
Для организации задержки таймера TIM5 нужно выполнить следующие:

. Подать тактирование на модуль таймера​

. Установить делитель частоты для таймера в регистре PSC​

. Установить источник генерации прерываний по событию переполнение с помощью бита URS в регистре CR1​

. Установить значение до которого счетчик будет считать в регистре перезагрузке ARR​

. Скинуть флаг генерации прерывания UIF по событию в регистре SR​

. Установить начальное значение счетчика в 0 в регистре CNT​

. Запустить счетчик с помощью бита EN в регистре CR1​

. Проверять, пока не будет установлен флаг генерации прерывания по событию UIF в регистре SR​

. Как только флаг установлен, остановить счетчик, сбросить бит EN в регистре CR1. Сбросить флаг генерации прерывания UIF по событию в регистре SR


== Программа с таймером TIM5

[source, cpp]
---- 
----

== Вывод по работе

* [*] Создана Архитиктура

* [*] Приведен листинг программы и новых классов 