:figure-caption: Рисунок
:table-caption: Таблица
i = "Темавфывфывфвф"
include::Tityl_list_2.adoc[]

<<Цель отчета>>

<<Указатель>>

<<Ссылка>>

<<Вывод по работе>>

== Цель отчета

. Изучить что такое указатель
.. Как берется адресс и разыменоввывается указатель;
.. Модификаторы типов данных;
.. Виды операций над указателем;
.. Сложные указатели
.. Константный указатель и указатель на константу

. Что такое ссылка 

== Указатель

* Указатель это переменная, значением которой является адрес ячейки памяти. 

То есть указатель ссылается на блок данных из области памяти, причём на самое его начало. Указатель может ссылаться на переменную или функцию. Для этого нужно знать адрес переменной или функции.

Чтобы узнать адрес конкретной переменной в С++ существует унарная операция взятия адреса "&". Такая операция извлекает адрес объявленных переменных, для того, чтобы его присвоить указателю. 

.Пример:

[source, cpp]
----
int main() 
{
  int c = 463 ;
  int* ptr = &c ;
  return 0;
}
----
* [*] Объявляем переменную c типа int.

* [*] Объявляем указатель ptr на переменную c типа int.

* [*] Размер занимаемый указателя для микроконтроллера STM32F411RE равен  4 байтам или же 32 битам. 

* Взятие адреса и разыменование указателя это операция позволяющая получить объект, значение переменной по адресу, которая хранится в указателе.

.Пример:
[source, cpp]

----
int main() 
{
  int  c = 463 ;              
  int* ptr = &c ;             
  cout << &c ;                
  cout << c ;                 

  *ptr = 5;                   
  cout << c << ": " << *ptr;  
}
----
Где через выражение *ptr мы можем получить значение по адресу, который хранится в указателе ptr, а через выражение типа *ptr = 5 значение вложить по этому адресу новое значение.

* Операции над указателями

С указателями можно выполнять следующие операции: 

* [*] Разадресация *; 

* [*] Присваивание; 

* [*] Сложение с константой; 

* [*] Вычитание;

* [*] Инкремент (++); 

* [*] Декремент (--); 

* [*] Сравнение; 

* [*] Приведение типов;

* [*] Операции с  получением адреса (&).


.Но указатели должны быть одинковых типов данных








