[.text-center]
Министерство науки и высшего образования Российской Федерации Федеральное государственное образовательное учреждение высшего образования
«Южно-Уральский государственный университет» (Национальный исследовательский университет)

[.text-center]
Высшая школа электроники и компьютерных наук Кафедра «Информационно-измерительная техника»

[.text-center]
дисциплина: 1.Ф.П1.06 (Программное обеспечение измерительных процессов)

[.text-center]
Отчет №1 +
на тему "Запуск программного обеспечения на микроконтроллере" 

[.text-right]
Работу принял, доцент +
___/ С.В. Колодий / +
___2023 г.

[.text-right]
Автор работы +
студент группы КЭ-413 +
___/ А.C. Нежурбида / +
___2023 г.

[.text-center]
Челябинск 2023

== Оглавление

<<1 Принцип запуска программного обеспечения на микроконтроллере>>

<<2 Ответы на вопросы по теме>>




== 1 Принцип запуска программного обеспечения на микроконтроллере

=== При подаче питания на микроконтроллер происходит:

.. Выполнение перехода на нулевой адрес, в нашем случае это адрес -  0x800000, по этому адресу лежит таблица векторов прерывания;
... Таблица векторов прерывания - это структура данных, которая связывает список обработчиков прерываний со списком запросов на прерывание.

.. Инициализация стека;
... Стек - это структура данных, которая работает по принципу первый пришел - последним ушел;
...  Стек нужен для оперативного сохранения каких-либо временных значений являясь областью памяти.

.. Переход на вектор прерываний Start, в нем прописан адрес функции, которая начинает выполнять свой код; 
... В векторе прерывания Start находится функция, которая начинает инициализацию глобальных переменных значений, которым присвоено нулевое "0" значение и переменные, которым не присвоены никакие значение. 
... Затем следует инициализация остальных переменных, которым присвоены какие-либо значения. Инициализация заданных переменных (initialized data, например, int i = 1), значения для каждой переменной будут скопированы из ПЗУ в ОЗУ.
... Следующим шагом запускается функция main.
.. После выполнения кода программы, с помощью счетчика, повышается адрес на единицу и контроллер переходит на следующий адрес, где лежит команда выполнение, микроконтроллер выполняет команду и переходит на следующий удрес. На такой системе построена логика работы микроконтроллера.

== 2 Ответы на вопросы по теме

1) Дайте определение понятию "Интегрированная среда разработки".
 
* Ответ: это совокупность программных средств для разработки ПО.

2) Что такое компилятор и чем он отличается от транслятора?

* Ответ: компилятор это программа, преобразующая код на языке программирования в машинный код. Он отличается от транслятора тем, что его конечная программа обязательно написана в виде машинного кода или языка ассемблера.

3) Что такое компоновщик и какие функции он выполняет?

* Ответ: компоновщик это программа, которая создает исполняемый файл для целевой платформы из объектов на входе (библиотеки, объектные файлы).

4) Почему важен процесс проектирования ПО? Какие задачи входят в этот процесс?

* Ответ: проектирование ПО важно, потому что оно позволяет:
 ** оценить затрачиваемые на это ресурсы до начала создания;
 ** избежать разногласий между заказчиком и исполнителем;
 ** обеспечить повторяемость;
 ** повысить качество ПО, вследствие того, что выявление ошибок в коде будет осуществляться на ранних этапах разработки.

* В процесс проектирования входят:
 ** составление и утверждение ТЗ;
 ** выбор описания, архитектуры и детальной архитектуры программы, метода и стратегии решения, выбор внутренних данных;
 ** создание "макетов" интерфейсов, принципиальных схем устройств, диаграмм структуры базы данных, определение схемы взаимодействия компонентов;
 ** кодирование, юнит-тестирование;
 ** системное тестирование;
 ** контроль экспертами;
 ** документирование ПО.

6) Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки?

* Ответ: отладка нужна для поиска и устранения ошибок в приложениях. Точки остановки применяются для контроля выполнения программы на определенных шагах алгоритма.
