[.text-center]
Министерство науки и высшего образования Российской Федерации Федеральное государственное образовательное учреждение высшего образования
«Южно-Уральский государственный университет» (Национальный исследовательский университет)
[.text-center]
Высшая школа электроники и компьютерных наук Кафедра «Информационно-измерительная техника»

[.text-center]
дисциплина: 1.Ф.П1.06 (Программное обеспечение измерительных процессов)

[.text-center]
Отчет по лабораторной работе №1

[.text-right]
Работу принял, доцент +
___/ С.В. Колодий / +
___2023 г.

[.text-right]
Автор работы +
студент группы КЭ-413 +
___/ А.С. Нежурбида / +
___2023 г.

[.text-center]
Челябинск 2023

:toc:
toc::[]
== Оглавление

<<Портируемость проекта>>

<<Типы данных>>

<<Задание 3>>

<<Вывод по работе>>

== Цель отчета

. Портируемость проекта
. Изучить типы данных
.. Встроенные типы;
.. Модификаторы типов данных;
.. Размеры типов данных;
.. Пользовательские типы;
.. Псевдонимы типов;
.. Неявное преобразование типов;
.. Явное преобразование типов.

. Память микроконтроллера CortexM4
.. Память для расположения данных;
.. Память под функции(команды).

== Портируемость проекта

Портируемость проекта - возможность переноса программного обеспечения с одного вида микроконтроллера на другой. Возможность перенос проекта на другие микроконтроллеры без каких либо серьезных проблем выполняется  за счет:

* [*] Использования одинаковых типов данных, в которых установлен  один размер. Это нужно для разных ядер
микроконтроллеров, чтобы  один и тот же тип переменной имел одинаковый размер.

* [*]  Разделять часть, которая отвечает за аппаратуру и аппаратные модули, зависящую от
микроконтроллера и бизнес логику, которая не зави   сит от аппаратуры
* [*]  Использовать разделение реализации и интерфейсо

== Типы данных

