=  Принцип запуска программного обеспечения на микроконтроллере

== При подаче питания на микроконтроллер происходит:

.. Выполнение перехода на нулевой адрес, по этому адресу лежит таблица векторов прерывания;
... Таблица векторов прерывания - это структура данных, которая связывает список обработчиков прерываний со списком запросов на прерывание.

.. Инициализация стека;
... Стек - это структура данных, которая работает по принципу первый пришел - последним ушел;
...  Стек нужен для оперативного сохранения каких-либо временных значений являясь областью памяти.

.. Переход на вектор прерываний Start, в нем прописан указатель на функцию, которая начинает выполнять свой код; 
... Вектор прерываний Start - инициализирует глобальные переменные значения, которым присвоено нулевое "0" значение  и переменные, которым не присвоены никакие значение.
... Затем следует инициализация остальных переменных, которым присвоены какие-либо значения.
... Следующим шагом запускается функция main.
.. После выполнения кода программы, с помощью счетчика, повышается адрес на единицу и контроллер переходит на выполнение следующей команды, прописанной в этом адресе.

=== Нежурбида А.С. КЭ-413.
