

[.text-center]
Министерство науки и высшего образования Российской Федерации Федеральное государственное образовательное учреждение высшего образования
«Южно-Уральский государственный университет» (Национальный исследовательский университет)

[.text-center]
Высшая школа электроники и компьютерных наук Кафедра «Информационно-измерительная техника»

[.text-center]
дисциплина: 1.Ф.П1.06 (Программное обеспечение измерительных процессов)

[.text-center]
Отчет №1 +
на тему "Запуск программного обеспечения на микроконтроллере" 

[.text-right]
Работу принял, доцент +
___/ С.В. Колодий / +
___2023 г.

[.text-right]
Автор работы +
студент группы КЭ-413 +
___/ А.C. Нежурбида / +
___2023 г.

[.text-center]
Челябинск 2023


:toc:
toc::[]
== Оглавление

<<1 Принцип запуска программного обеспечения на микроконтроллере>>

<<2 Ответы на вопросы по теме>>




== 1 Принцип запуска программного обеспечения на микроконтроллере

* При подаче питания на микроконтроллер происходит:

. Выполнение перехода на нулевой адрес, в нашем случае это адрес -  0x800000, по этому адресу лежит таблица векторов прерывания;
. Таблица векторов прерывания - это структура данных, которая связывает список обработчиков прерываний со списком запросов на прерывание.

* Инициализация стека:
. Стек - это структура данных, которая работает по принципу первый пришел - последним ушел;
.  Стек нужен для оперативного сохранения каких-либо временных значений являясь областью памяти.

. Переход на вектор прерываний Start, в нем прописан адрес функции, которая начинает выполнять свой код; 
. В векторе прерывания Start находится функция, которая начинает инициализацию глобальных переменных значений, которым присвоено нулевое "0" значение и переменные, которым не присвоены никакие значение. 
. Затем следует инициализация остальных переменных, которым присвоены какие-либо значения. Инициализация заданных переменных (initialized data, например, int i = 1), значения для каждой переменной будут скопированы из ПЗУ в ОЗУ.
. Следующим шагом запускается функция main.
. После выполнения кода программы, с помощью счетчика, повышается адрес на единицу и контроллер переходит на следующий адрес, где лежит команда выполнение, микроконтроллер выполняет команду и переходит на следующий удрес. На такой системе построена логика работы микроконтроллера.

== 2 Ответы на вопросы по теме
[qanda]
Дайте определение понятию "Интегрированная среда разработки"::
Данные среды являются программными средства для разработки ПО.

Что такое компилятор и чем он отличается от транслятора?::
Компилятор является программой, в которой выполняются преобразования кода в язык машинного кода. Отличия от транслятора тем, что конечная программа обязательно написана в виде машинного кода или языка ассемблера.

Что такое компоновщик и какие функции он выполняет?::
Компоновщик это программа, которая создает исполняемый файл для целевой платформы из объектов на входе (библиотеки, объектные файлы).

Почему важен процесс проектирования ПО? Какие задачи входят в этот процесс?::
. Проектирование ПО важно, так как позволяет выполинть следующие действия:
 .. оценить затрачиваемые на это ресурсы до начала создания;
 .. избежать разногласий между заказчиком и исполнителем;
 .. обеспечить повторяемость;
 .. повысить качество ПО, вследствие того, что выявление ошибок в коде будет осуществляться на ранних этапах разработки.

. В процесс проектирования входят:
 .. составление и утверждение ТЗ;
 .. выбор описания, архитектуры и детальной архитектуры программы, метода и стратегии решения, выбор внутренних данных;
 .. создание "макетов" интерфейсов, принципиальных схем устройств, диаграмм структуры базы данных, определение схемы взаимодействия компонентов;
 .. кодирование, юнит-тестирование;
 .. системное тестирование;
 .. контроль экспертами;
 .. документирование ПО.

Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки?::
Отладка нужна для поиска и устранения ошибок в приложениях. Точки остановки применяются для контроля выполнения программы на определенных шагах алгоритма.